#' attach_file
#'
#' Attach a file in DDH
#'
#' @param credentials list: object returned by the get_credentials() function
#' @param body json: json object generated by jsonlite::toJSON
#' @param root_url character: API root URL
#'
#' @return list
#' @export
#'

attach_file <- function(credentials, file_path = "C:/Users/wb523589/ddh/GDP.csv", resource_id = 94673, root_url = production_root_url) {
  # construct the body pf the POST request
  body = list('files[1]' = httr::upload_file("C:/Users/wb523589/ddh/GDP.csv"), 'field_name' = c('field_upload'), 'attach' = c(1))
  
  # credentials
  cookie <- credentials$cookie
  token <- credentials$token
  
  # build query
  path <- paste0('api/dataset/node/', resource_id, '/attach_file')
  url <- httr::modify_url(root_url, path = path)
  
  out <- httr::POST(url = url,
                    httr::add_headers(.headers = c('Content-Type' = 'multipart/form-data',
                                                   'Cookie' =  cookie,
                                                   'X-CSRF-Token' = token)),
                    body = body)
  
  out <- httr::content(out)
  return(out)
}