#' create_resource
#'
#' Create new resource in DDH
#'
#' @param body json: json object generated by jsonlite::toJSON
#' @param root_url character: API root URL
#' @param credentials list: authentication token and cookie
#'
#' @return list
#' @export
#'

create_resource <-
  function(body,
           root_url = dkanr::get_url(),
           credentials = list(cookie = dkanr::get_cookie(),
                              token = dkanr::get_token())) {

    out <- dkanr::create_node(url = root_url,
                              body = body,
                              credentials = credentials)

    return(jsonlite::fromJSON(out))
  }
