#' create_resource
#'
#' Create new resource in DDH
#'
#' @param root_url character: API root URL
#' @param body json: json object generated by jsonlite::toJSON
#' @param credentials list: authentication token and cookie
#'
#' @return list
#' @export
#'

create_resource <-
  function(root_url = dkanr::get_url(),
           body,
           credentials = list(cookie = dkanr::get_cookie(),
                              token = dkanr::get_token())) {

    out <- dkanr::create_node(root_url, body, credentials)

    return(jsonlite::fromJSON(out))
  }
