#' create_resource
#'
#' Create new resource in DDH
#'
#' @param credentials list: object returned by the get_credentials() function
#' @param body json: json object generated by jsonlite::toJSON
#' @param root_url character: API root URL
#'
#' @return list
#' @export
#'

create_resource <- function(credentials, body, root_url = production_root_url) {
  cookie <- credentials$cookie
  token <- credentials$token

  # Build url
  path <- 'api/dataset/node'
  url <- httr::modify_url(root_url, path = path)

  # CHECK: dataset_id
  out <- httr::POST(url = url,
                    httr::add_headers(.headers = c('Content-Type' = 'application/json',
                                                   'Cookie' =  cookie,
                                                   'X-CSRF-Token' = token)),
                    body = body,
                    encode = 'json')

  err_handler(out)

  out <- httr::content(out)

  return(out)
}
