#' download_resource
#'
#' Download a file, extracting the path from `get_metadata()` output
#'
#' @param resource_id character: Resource NID
#' @param credentials Optional list parameter. Default values are Cookie and Token generated by dkan_setup()
#'
#' @export
#'

download_resource <- function(resource_id,
                              credentials = list(cookie = dkanr::get_cookie(),
                                                 token = dkanr::get_token())){

  resource <- get_metadata(nid = resource_id,
                           credentials = credentials)

  path_locs <- c(resource[[1]]$field_link_api$und[[1]]$url,
                resource[[1]]$field_link_remote_file$und[[1]]$url,
                resource[[1]]$field_upload$und[[1]]$uri)

  path <- unname(unlist(path_locs))

  ext <- tools::file_ext(path)

  if (resource[[1]]$type == "resource") {
    if (ext != "") {
      utils::download.file(url = path, destfile = basename(path))
      out <- ext
    } else {
      warning("This resource cannot be downloaded")
      out <- path
    }
  } else {
    warning("This is a dataset, not a resource. Please enter the nid for a resource.")
    out <- resource[[1]]$title
  }
  return(out)
}
