#' update_resource
#'
#' Update existing resource in DDH
#'
#' @param credentials list: object returned by the get_credentials() function
#' @param nid character: Node ID of the resource to be updated
#' @param body json: json object generated by jsonlite::toJSON
#' @param root_url character: API root URL
#'
#'
#' @return list
#' @export
#'

update_resource <- function(credentials, nid, body, root_url = production_root_url) {
  cookie <- credentials$cookie
  token <- credentials$token

  # Build url
  path <- paste0('api/dataset/node/', nid)
  url <- httr::modify_url(root_url, path = path)

  out <- httr::PUT(url = url,
                   httr::add_headers(.headers = c('Content-Type' = 'application/json',
                                                  'Cookie' =  cookie,
                                                  'X-CSRF-Token' = token)),
                   body = body,
                   encode = 'json')

  httr::warn_for_status(out)

  out <- httr::content(out)
  # CHECK response is as expected
  assertthat::assert_that(all(names(out) %in% c('nid', 'uri')),
                          msg = "Unexpected response from DDH API")

  names(out) <- c('node_id', 'uri')

  return(out)
}
